image:
  repository: govukpay/toolbox
  tag: latest

service:
  port: 3040

env:
  PORT: '3040'
  COOKIE_SESSION_ENCRYPTION_SECRET: 'aezoor3eig0Looche1waeh1caiph3Mek # pragma: allowlist secret'
  NODE_ENV: 'development'
  TOOLBOX_FILE_ROOT: '.'
  BUILD_FOLDER_ROOT: './dist'
  AUTH_GITHUB_ENABLED: 'false'
  PUBLIC_AUTH_URL: 'http://publicauth:9600'
  PRODUCTS_URL: 'http://products:18000'
  ADMINUSERS_URL: 'http://adminusers:9700'
  LEDGER_URL: 'http://ledger:10700'
  WEBHOOKS_URL: 'http://webhooks:10800'
  CONNECTOR_URL: 'http://connector:9300'
  SELFSERVICE_URL: 'http://selfservice:9400'
