image:
  repository: govukpay/toolbox
  tag: latest

service:
  port: 3040

env:
  COOKIE_SESSION_ENCRYPTION_SECRET: 'aezoor3eig0Looche1waeh1caiph3Mek # pragma: allowlist secret'
  NODE_ENV: 'development'
  TOOLBOX_FILE_ROOT: '.'
  BUILD_FOLDER_ROOT: './dist'
  AUTH_GITHUB_ENABLED: 'false'
  PUBLIC_AUTH_URL: 'http://publicauth:9600'
