image:
  repository: govukpay/ledger
  tag: latest

service:
  port: 10700
  adminPort: 10701

env:
  PORT: '10700'
  ADMIN_PORT: '10700'
  PORT: '10700'
  ADMIN_PORT: '10701'
  QUEUE_MESSAGE_RECEIVER_THREAD_DELAY_IN_MILLISECONDS: '1000'
  EXPUNGE_AND_REDACT_HISTORICAL_DATA_ENABLED: 'true'
  EXPUNGE_OR_REDACT_DATA_OLDER_THAN_DAYS: '0'
  EXPUNGE_NO_OF_TRANSACTIONS_PER_TASK_RUN: '5'
  SNS_ENABLED: 'true'
  PUBLISH_CARD_PAYMENT_EVENTS_TO_SNS: 'true'
  PUBLISH_CARD_PAYMENT_DISPUTE_EVENTS_TO_SNS: 'true'
